<html>
<body>
<h1 style="background-color: #022851;"><center>
    <br><font size="+3.5">
    <font color=#FFBF00><b>Introduction to Machine Learning</b></font>
   </font>
    <br><font size="+1">
    <font color=#FFBF00><b>WEEK 4 | PROBLEM SET 1 </b></font>
   </font>
    <br><font size="+1">
    <font color=#FFBF00><b>Name:</b> Blue Ferdinand Alday </font> <br>
    <font color=#FFBF00><b>Due Date:</b> 10/5/2024 </font>
   </font> 
    </center>
</h1>
</body>
</html>

#### 1. Take the iris data. Use Naïve Bayes algorithm to find the species with the following two observations.
#### Testing data =  [4.5 3.0 5.6 2.1; 5.4 2.6 4.5 0.0]
#### Predict that the species are Iris-sentosa since the conditional probability below is the maximum of all the classes.


In [ ]:
"""
What assumptions are made about the attributes in Naïve Bayes method of classification and why? 

As mentioned in this week's videos titled "Classifier Performance" and "Naive Bayes Assumptions and Why", the assumptions made in Naive Bayes are that all features are independent of each other and equally important. 
These are made to limit or significantly reduce the number of combinations calculated in the probability that given X event has happened, what is the likelihood that event Y will happen. 
The advantages are fast and easy training cycles, straightforward test cycles, fast performance requiring low computational power, and it is a popular generative model.

What is Laplacian correction and why it is necessary?
Laplacian correction is a smoothing techique used when the test data has zero frequency to predict the class of the test data.


Use Naïve Bayes algorithm from scratch for the following
questions:



1. Take the iris data as the TRAINING DATA. Use Naïve Bayes algorithm to find
the species with the following two observations.
TESTING DATA =  [4.5 3.0 5.6 2.1; 5.4 2.6 4.5 0.0]

Predicted that OBSERVATION 1 [4.5 3.0 5.6 2.1] is species Iris-virginica with the highest posterior of 9.8740030532198296358134772407954e-5 
(see manual calculations below)
Predicted that OBSERVATION 2 [5.4 2.6 4.5 0.0] is species Iris-versicolor with the highest posterior of 2.5973740972777462808311007883727e-11
(see manual calculations below)

Show various steps involved and do as explained in the lectures:

******************************************************************************************************************************************************************************************************************************

Use IRIS CSV to calculate Mean, Variance of Various Species (training data)

p(Iris-setosa) = 0.333
mean(SL|Iris-sentosa)		5.006
variance(SL|Iris-sentosa)		0.12424898

p(SL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.1 - 5.006)**2 / 0.248497959) / sqrt ( 0.248497959 * pi )
= exp (-0.03555763610919637372152420777025) / 0.78067936242645764298996717848981
= 1.280935615989468434780051963103 * 0.96506710991370246134644174414557 = 
= 1.2361888329084845019558376267834


mean(SW|Iris-sentosa)		3.418
variance(SW|Iris-sentosa)		0.145179592

p(SW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.5 - 3.418)**2 / 0.290359184) / sqrt ( 0.91219027935672703544873054725204)
= exponent(-0.006724)/ 0.95508652977451578936930846360501
= 1.0400089672919846899748207000906

mean(PL|Iris-sentosa)		1.464
variance(PL|Iris-sentosa)		0.030106122

p(PL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(1.4 - 1.464)**2 / 0.060212245) / sqrt ( 0.18916234654814875997365610674165)
= exp(-0.06802603025348083267780498800535) / 0.43492797857593475354896031360409
= 2.2992312503653025891767109663462 * 0.93423615485678180576751395551209
= 2.1480249624678308885237754128998

mean(PW|Iris-sentosa)		0.244
variance(PW|Iris-sentosa)		0.011493878

p(PW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(0.2 - 0.244)**2 / 0.022987755) / sqrt ( 0.0722181622305220374664358227472)
= 3.7211466317769604813258743759693 * exponent(-0.08421875037384033369069750395374) 
= 3.7211466317769604813258743759693 * 0.9192301521607157248757126696308
= 3.4205901845406701916420275254319

1.2361888329084845019558376267834 * 1.0400089672919846899748207000906 * 2.1480249624678308885237754128998 * 3.4205901845406701916420275254319 * 0.333  = 9.4463116423181180036716883794361 * 0.333 = 3.1487390597338982741638838875174


p(Iris-versicolor) = 0.333
mean(SL|Iris-versicolor)		5.936
variance(SL|Iris-versicolor)		0.266432653


p(SL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(7 - 5.936)**2 / 0.532865306) / sqrt ( 1.6740457306824771724901274360001 )
= exponent(-2.1245443965909088477980212132632) * 0.77288760271970533790644143960937
= 0.11948739473171984826321979369897 * 0.09235032606942210266091659523059 
= 0.09235032606942210266091659523059

mean(SW|Iris-versicolor)		2.77
variance(SW|Iris-versicolor)		0.098469388


p(SW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.2 - 2.77)**2 / 0.196938776) / sqrt ( 0.61870141188856588647590910962756)
= 0.77288760271970533790644143960937 * exponent(-0.93887046398622889785808357009389)
= 0.3022526237073982571508794601964

mean(PL|Iris-versicolor)		4.26
variance(PL|Iris-versicolor)		0.220816327

p(PL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.7 - 4.26)**2 / 0.441632653) / sqrt ( 1.3874298982501703616237188387506)
= exp(-0.4383733826855415964906018849109) * 0.84897416692048826762806533111854
= 0.54766039380429274627604818308822

mean(PW|Iris-versicolor)		1.326
variance(PW|Iris-versicolor)		0.039106122

p(PW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(1.4 - 1.326)**2 / 0.078212245) / sqrt ( 0.24571101431276503826598368764069)
= 2.0173798915494976521935336491961 * exponent(-0.07001461216207257572008066000407) 
= 0.93238019571587597430088786197028 * 2.0173798915494976521935336491961
= 1.8809650581161932685022652049014
(0.09235032606942210266091659523059 * 0.3022526237073982571508794601964 * 0.54766039380429274627604818308822 *1.8809650581161932685022652049014 ) * 0.333   = 0.00957513285287130430896777558624


p(Iris-virginica) = 0.333
mean(SL|Iris-virginica)		6.588
variance(SL|Iris-virginica)		0.404342857


p(SL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(6.3 - 6.588)**2 / 0.808685714) / sqrt ( 2.5405610981654166081585350267348 )
= exponent(-0.1025664217434166272411732006929) * 0.62738651262194577989406934630067
= 0.90251820092962395208163004206336 * 0.62738651262194577989406934630067 
= 0.56622774665906931511391636234862

mean(SW|Iris-virginica)		2.974
variance(SW|Iris-virginica)		3.549837374

p(SW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.3 - 2.974)**2 / 7.099674747) / sqrt ( 22.304286028052173952064578331136)
= 0.21174142772191343846214525890851 * exponent(-0.01496913644458253659208087099712)
= 0.20859544645522863218909166712001

mean(PL|Iris-virginica)		5.552
variance(PL|Iris-virginica)		0.304587755

p(PL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(6 - 5.552)**2 / 0.60917551) / sqrt (1.9137813069628156268350323989574)
= 0.72285942155738867273155680783901 * exp(-0.12226396155904)
= 0.63966896734373185754252876630062

mean(PW|Iris-virginica)		2.026
variance(PW|Iris-virginica)		0.075432653

p(PW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.5 - 2.026)**2 / 0.150865306) / sqrt (2.0095793285364373610513654937457)
= 0.70541943808638686476201582240118 * exponent(-1.4892489595984380928508506786842) 
= 0.70541943808638686476201582240118 * 0.22554198308711157387644463024489
= 0.15910169897419961627832021991888
(0.56622774665906931511391636234862 * 0.20859544645522863218909166712001 * 0.63966896734373185754252876630062 *0.15910169897419961627832021991888 ) * 0.333  = 0.00400285910400528887182199168569


******************************************************************************************************************************************************************************************************************************
Now use the prediction of the first observation 4.5 3.0 5.6 2.1:

p(SL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(0.256036/ 0.248497959) / sqrt ( 0.248497959 * pi )
= exp (-1.0303344181591447195749402513201) / 0.78067936242645764298996717848981
= 1.280935615989468434780051963103 * 0.35688759091939372861894749424926 = 
= 0.45715002611333102717509060798867

p(SW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.0 - 3.418)**2 / 0.290359184) / sqrt ( 0.91219027935672703544873054725204)
= exponent(-0.60175124338412522884070372645764)/ 0.95508652977451578936930846360501
= 0.57361438711516018224949870534351

p(PL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.6 - 1.464)**2 / 0.060212245) / sqrt ( 0.18916234654814875997365610674165)
= exp(-284.10327500660372321277839748377) / 0.43492797857593475354896031360409
= 4.1258684239946351442408779040487e-124 * 2.2992312503653025891767109663462
= 9.4863256153439053738745601409463e-124

p(PW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.1 - 0.244)**2 / 0.022987755) / sqrt ( 0.0722181622305220374664358227472)
= 3.7211466317769604813258743759693 * exponent(-149.85090975608535935762322158036) 
= 3.7211466317769604813258743759693 * 8.3286916708617595467644365308154e-66
= 3.09922829581360616935821235301e-65

posterior (Iris-setosa) = 0.45715002611333102717509060798867 * 0.57361438711516018224949870534351 * 9.4863256153439053738745601409463e-124 * 3.09922829581360616935821235301e-65 * 0.333 = 2.5672881372915766943449095464844e-189


p(SL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.5 - 5.936)**2 / 0.532865306) / sqrt ( 1.6740457306824771724901274360001 )
= exponent(-3.8698259706177981120054380121343) * 0.77288760271970533790644143960937
= 0.02086199971023849620255783456093 * 0.77288760271970533790644143960937
= 0.01612398094398541872894231133042

p(SW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.0 - 2.77)**2 / 0.196938776) / sqrt ( 0.61870141188856588647590910962756)
= 0.77288760271970533790644143960937 * exponent(-0.26861139829568149646669886889111)
= 0.59082640053362232466331409518064

p(PL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.6 - 4.26)**2 / 0.441632653) / sqrt ( 1.3874298982501703616237188387506)
= exp(-4.0658225513954467492692393829856) * 0.84897416692048826762806533111854
= 0.01455895410582821778168329957692

p(PW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.1 - 1.326)**2 / 0.078212245) / sqrt ( 0.24571101431276503826598368764069)
= 2.0173798915494976521935336491961 * exponent(-7.6596190276854986070275824456899) 
= 4.7148700007799806558944662738491e-4 * 2.0173798915494976521935336491961
= 9.5116839308434972863968104147965e-4

posterior (Iris-versicolor) = 0.01612398094398541872894231133042 * 0.59082640053362232466331409518064 * 0.01455895410582821778168329957692 * 9.5116839308434972863968104147965e-4 * 0.333  = 4.3930281915128308124820248037169e-8


p(SL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.5 - 6.588)**2 / 0.808685714) / sqrt ( 2.5405610981654166081585350267348 )
= exponent(-5.3911475428883364693641663614204) * 0.62738651262194577989406934630067
= 0.00285883801948563838738495712434

p(SW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(3.0 - 2.974)**2 / 7.099674747) / sqrt ( 22.304286028052173952064578331136)
= 0.21174142772191343846214525890851 * exponent(-9.521562946044068967825914405935e-5)
= 0.21172126758838517702589429301545

p(PL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.6 - 5.552)**2 / 0.60917551) / sqrt (1.9137813069628156268350323989574)
= 0.72285942155738867273155680783901 * exp(-0.00378216123625849634040606786704)
= 0.72013061432129142124645240362926

p(PW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.1 - 2.026)**2 / 0.150865306) / sqrt (2.0095793285364373610513654937457)
= 0.70541943808638686476201582240118 * exponent(-0.03629727831526752744597223698337) 
= 0.68027375308674345651893153166432

posterior (Iris-virginica) = 
0.00285883801948563838738495712434 * 0.21172126758838517702589429301545 * 0.72013061432129142124645240362926
* 0.68027375308674345651893153166432 * 0.333  
= 9.8740030532198296358134772407954e-5



******************************************************************************************************************************************************************************************************************************
Now use the prediction of the second observation [5.4 2.6 4.5 0.0]:

p(SL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.4 - 5.006)**2 / 0.248497959) / sqrt ( 0.248497959 * pi )
= 0.53542348538895351538303347384365 * 1.1317842621230728329233937699423
= 0.60598387433430062252062802885893

p(SW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.6 - 3.418)**2 / 0.290359184) / sqrt ( 0.91219027935672703544873054725204)
= exponent(-2.3044699327226368389661384220743) * 1.0470255509059349102705800603213
= 0.10450539342251626014188551478466

p(PL|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.5 - 1.464)**2 / 0.060212245) / sqrt ( 0.18916234654814875997365610674165)
= exp(-39.139945703735178782986749622108) / 0.43492797857593475354896031360409
= 1.0040088913570070336329178588052e-17 / 0.43492797857593475354896031360409
= 2.3084486186526525257677595437372e-17

p(PW|Iris-setosa) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(0 - 0.244)**2 / 0.022987755) / sqrt ( 0.0722181622305220374664358227472)
= 3.7211466317769604813258743759693 * exponent(-2.5899005796781808401907885306764) 
= 3.7211466317769604813258743759693 * 0.07502749897263147422889182279679
= 0.27918832509265697324585642472459

posterior (Iris-setosa) = 0.60598387433430062252062802885893 * 0.10450539342251626014188551478466 * 2.3084486186526525257677595437372e-17 * 0.27918832509265697324585642472459 * 0.333 = 1.3591314788037011082665969428259e-19


p(SL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.4 - 5.936)**2 / 0.532865306) / sqrt ( 1.6740457306824771724901274360001 )
= exponent(-0.53915313450712814844057421144998) * 0.77288760271970533790644143960937
= 0.45078048860707545497835506612157

p(SW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.6 - 2.77)**2 / 0.196938776) / sqrt ( 0.61870141188856588647590910962756)
= 0.77288760271970533790644143960937 * exponent(-0.14674611362467287803190165049061)
= 0.66739863456001760085558037811815

p(PL|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.5 - 4.26)**2 / 0.441632653) / sqrt ( 1.3874298982501703616237188387506)
= exp(-0.13042513865024378077406337071729) * 0.84897416692048826762806533111854
= 0.74516347179882203623223358457735

p(PW|Iris-versicolor) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(0 - 1.326)**2 / 0.078212245) / sqrt ( 0.24571101431276503826598368764069)
= 2.0173798915494976521935336491961 * exponent(-22.480827650452943781373364234718) 
= 1.7246485308430539282505852551049e-10 * 2.0173798915494976521935336491961
= 3.4792712661131605904385727404675e-10

posterior (Iris-versicolor) = 0.45078048860707545497835506612157 * 0.66739863456001760085558037811815 * 0.74516347179882203623223358457735 * 3.4792712661131605904385727404675e-10 * 0.333  = 2.5973740972777462808311007883727e-11


p(SL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(5.4 - 6.588)**2 / 0.808685714) / sqrt ( 2.5405610981654166081585350267348 )
= exponent(-1.7452317699778235479005877430401) * 0.62738651262194577989406934630067
= 0.10954451850171539157045785678574

p(SW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(2.6 - 2.974)**2 / 7.099674747) / sqrt ( 22.304286028052173952064578331136)
= 0.21174142772191343846214525890851 * exponent(-0.01970174761303047619739079295036)
= 0.2076105776544151228177043255165

p(PL|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(4.5 - 5.552)**2 / 0.60917551) / sqrt (1.9137813069628156268350323989574)
= 0.72285942155738867273155680783901 * exp(-1.8167243788247495372885229742739)
= 0.11750611640600297646470421063418

p(PW|Iris-virginica) = exponent( -((x - mean) ** 2) / (2 * SL variance) ) / sqrt ( 2 * pi * SL variance)
= exponent(-(0 - 2.026)**2 / 0.150865306) / sqrt (2.0095793285364373610513654937457)
= 0.70541943808638686476201582240118 * exponent(-27.207554266983026568083188059155) 
= 1.0773498075170365359644254915171e-12

posterior (Iris-virginica) = 0.10954451850171539157045785678574 * 0.2076105776544151228177043255165 * 0.11750611640600297646470421063418 * 1.0773498075170365359644254915171e-12 * 0.333  = 9.58741601354740531102927683361e-16
"""

In [90]:
# importing necessary libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

In [91]:
# loading the iris dataset
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [92]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [93]:
# set X as the input
X = iris.data

# set y as the target
y = iris.target

In [94]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [95]:
# Verify row count is 150
y.shape[0]

150

In [96]:
# show labels
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [97]:
# dividing X, y into train and test data
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 893)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [98]:
y_train

array([2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 2,
       2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 2, 1, 1, 1, 2, 1, 2,
       2, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 1, 2, 1,
       0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0,
       1, 1, 1, 2, 0, 2, 2, 1, 0, 1])

In [99]:
y_test

array([0, 1, 2, 1, 0, 0, 1, 2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 1, 2, 1,
       0, 0, 1, 1, 2, 0, 1, 2])

In [100]:
X_train

array([[6.4, 2.8, 5.6, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [6.3, 2.8, 5.1, 1.5],
       [4.4, 2.9, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.6, 2.8, 4.9, 2. ],
       [6.3, 3.4, 5.6, 2.4],
       [4.8, 3.4, 1.6, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 2.7, 3.9, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.2, 3.4, 1.4, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 2.6, 6.9, 2.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.9, 3. , 4.2, 1.5],
       [5. , 3. , 1.6, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [6.7, 3.1, 5.6, 2.4],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 2.5, 3. , 1.1],
       [6. , 2.9, 4.5, 1.5],
       [4.9, 3

In [101]:
X_test

array([[4.6, 3.4, 1.4, 0.3],
       [5. , 2. , 3.5, 1. ],
       [7.7, 3. , 6.1, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.6, 1.4],
       [6.7, 2.5, 5.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.3, 2.7, 4.9, 1.8],
       [5.1, 3.8, 1.6, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.6, 4. , 1.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.4, 3.2, 5.3, 2.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.3, 2.3, 4.4, 1.3],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.8, 1.5, 0.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.1, 3. , 4.9, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.7, 2.5, 5. , 2. ]])

### Gaussian Naive Bayes

In [102]:
# training a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

gnb_model = GaussianNB().fit(X_train, y_train)

In [103]:
# Display the accuracy of the model
gnb_model.score(X, y)

0.9666666666666667

In [104]:
# provide the 2 observations to set up the prediction
X_test_new = np.array([[4.5, 3.0, 5.6, 2.1], [5.4, 2.6, 4.5, 0.0]])

In [105]:
label = iris.target
y_pred_gnb = gnb_model.predict(X_test_new)
y_pred_gnb

array([2, 1])

These predictions match the predictions made with manual calculations on the top section of this notebook

#### 2. Consider the data of play tennis or not. Predict theoutput for the following case and verify your answer with sklearn:

In [ ]:
"""
2. Consider the data of play tennis or not. Predict the
output for the following case and verify your answer with sklearn (I used the example in one of the lecture slides and 
manually entered the corresponding values to get these manual calculations):

	a)Outlook: Sunny, Temp: Hot, Humidity: High, Wind= Strong (Predict that the answer is "x prime = no")

		1) Calculate priori probability for given class labels
		Prior Probability for Yes: 9/14
		Prior Probability for No: 5/14

		2) Calculate conditional probability with each attribute for each class
		P(Outlook =Sunny | Play=Yes) = 2/9; P(Outlook =Sunny | Play=No) = 3/5
		P(Temp=Hot | Play=Yes) = 2/9; P(Temp=Hot | Play=No) = 2/5
		P(Humidity=High | Play=Yes) = 3/9; P(Humidity=High | Play=No) = 4/5
		P(Wind=Strong | Play=Yes) = 3/9; P(Wind=Strong | Play=No) = 3/5

		3) Multiply same class conditional probability
		P(Yes| x prime) = (2/9 * 2/9 * 3/9 * 3/9) = 0.04938271604938271604938271604938 * 0.11111111111111111111111111111111 = 0.00548696844993141289437585733882
		P(No | x prime) = (3/5 * 2/5 * 4/5 * 3/5) = 0.36 * 0.4 * 0.8 = 0.1152

		4) Prior Probability (Yes) = 9/14, Prior Probability for No: 5/14
		P(Yes| x prime) = 0.00548696844993141289437585733882 * 9/14 = 0.00352733686067019400352733686066
		P(No| x prime) = 0.1152 * 5/14 = 0.04114285714285714285714285714286

		5) Class with high probability belongs to input set
		x prime = No


	b) • Outlook = Overcast, Temp = Mild, humidity = High, Wind = Strong  (Predict that the answer is "x prime = yes")

		1) Calculate priori probability for given class labels
		Prior Probability for Yes: 9/14
		Prior Probability for No: 5/14

		2) Calculate conditional probability with each attribute for each class
		P(Outlook =Overcast | Play=Yes) = 4/9; P(Outlook =Overcast | Play=No) = 0/5
		P(Temp=Mild | Play=Yes) = 4/9; P(Temp=Mild | Play=No) = 2/5
		P(Humidity=High | Play=Yes) = 3/9; P(Humidity=High | Play=No) = 4/5
		P(Wind=Strong | Play=Yes) = 3/9; P(Wind=Strong | Play=No) = 3/5

		3) Multiply same class conditional probability
		P(Yes| x prime) = (4/9 * 4/9 * 3/9 * 3/9) = 0.19753086419753086419753086419753 * 0.11111111111111111111111111111111 = 0.02194787379972565157750342935528
		P(No | x prime) = (0/5 * 2/5 * 4/5 * 3/5) = 0

		4) Prior Probability (Yes) = 9/14, Prior Probability for No: 5/14
		P(Yes| x prime) = 0.02194787379972565157750342935528 * 9/14 = 0.01410934744268077601410934744268
		P(No| x prime) = 0 * 5/14 = 0

		5) Class with high probability belongs to input set
		x prime = Yes

"""

In [76]:
# Assigning features and label variables
weather = [
    "Sunny",
    "Sunny",
    "Overcast",
    "Rainy",
    "Rainy",
    "Rainy",
    "Overcast",
    "Sunny",
    "Sunny",
    "Rainy",
    "Sunny",
    "Overcast",
    "Overcast",
    "Rainy",
]
outlook = weather
temp = [
    "Hot",
    "Hot",
    "Hot",
    "Mild",
    "Cool",
    "Cool",
    "Cool",
    "Mild",
    "Cool",
    "Mild",
    "Mild",
    "Mild",
    "Hot",
    "Mild",
]

humidity = [
    "High",
    "High",
    "High",
    "High",
    "Normal",
    "Normal",
    "Normal",
    "High",
    "Normal",
    "Normal",
    "Normal",
    "High",
    "Normal",
    "High",
]
wind = [
    "Weak",
    "Strong",
    "Weak",
    "Weak",
    "Weak",
    "Strong",
    "Strong",
    "Weak",
    "Weak",
    "Weak",
    "Strong",
    "Strong",
    "Weak",
    "Strong",
]
play = [
    "No",
    "No",
    "Yes",
    "Yes",
    "Yes",
    "No",
    "Yes",
    "No",
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "No",
]

tennis_data = pd.DataFrame(
    zip(outlook, temp, humidity, wind, play),
    columns=["Outlook", "Temperature", "Humidity", "Wind", "Play Tennis"],
)
tennis_data.to_csv("tennis_data.csv", index=False)

In [77]:
tennis_data.head()

Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3     Rainy        Mild     High    Weak         Yes
4     Rainy        Cool   Normal    Weak         Yes

#### This section is taken from the Resource file and updated to fit the HW assignment 


In [78]:
# Import LabelEncoder
from sklearn.preprocessing import LabelEncoder

# creating labelEncoder
le = LabelEncoder()

# Converting string labels into numbers.
# leave weather alone as it was part of the lesson
# re-use variables for Temp, Humidity, and Play
# add Outllok and Wind for the assignment
weather_encoded = le.fit_transform(weather)
print("Weather:", weather_encoded)

outlook_encoded = le.fit_transform(outlook)
print("Outlook:", outlook_encoded)

temp_encoded = le.fit_transform(temp)
print("Temp:", temp_encoded)

humidity_encoded = le.fit_transform(humidity)
print("Humidity:", humidity_encoded)

wind_encoded = le.fit_transform(wind)
print("Wind:", wind_encoded)

label = le.fit_transform(play)
print("Play:", label)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Outlook: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Humidity: [0 0 0 0 1 1 1 0 1 1 1 0 1 0]
Wind: [1 0 1 1 1 0 0 1 1 1 0 0 1 0]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Now combine the four features (outlook, temp, humidity, and wind) in a single variable 

In [79]:
X = pd.DataFrame(zip(outlook_encoded, temp_encoded, humidity_encoded, wind_encoded))
X.columns = ["Outlook", "Temp", "Humidity", "Wind"]
X

Outlook  Temp  Humidity  Wind
0         2     1         0     1
1         2     1         0     0
2         0     1         0     1
3         1     2         0     1
4         1     0         1     1
5         1     0         1     0
6         0     0         1     0
7         2     2         0     1
8         2     0         1     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
12        0     1         1     1
13        1     2         0     0

In [80]:
# dividing X, y into train and test data
X_train, X_test, y_train, y_test = train_test_split(
    X, label, test_size=0.2, random_state=123
)

In [81]:
y_test

array([0, 1, 1], dtype=int64)

In [82]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Create a Gaussian Classifier
nb_model = GaussianNB()

In [83]:
nb_model.fit(X_train, y_train)

GaussianNB()

In [84]:
y_pred = nb_model.predict(X_test)
y_pred

array([0, 0, 1], dtype=int64)

In [85]:
print("Accuracy mnb: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nCOnfusion Matrix gnb:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report gnb:\n", classification_report(y_test, y_pred))

Accuracy mnb: 66.67%

COnfusion Matrix gnb:
 [[1 0]
 [1 1]]

Classification Report gnb:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3



In [86]:
nb_model.predict_proba(X_test)

array([[0.5766177 , 0.4233823 ],
       [0.74407116, 0.25592884],
       [0.06572255, 0.93427745]])

#### Generating Model

Generate a model using Naive Bayes classifier


In [87]:
# Train the model using the training sets
nb_model.fit(X.values, label)

GaussianNB()

In [88]:
# Predict output and verify it matches our prediction made manually using Naive Bayes step by step in Assignment4.txt
# Outlook: Sunny (2), Temp: Hot (1), Humidity: High (0), Wind= Strong (0)
# Outlook = Overcast (0), Temp = Mild (2), humidity = High (0), Wind = Strong (0)
pred = nb_model.predict([[2, 1, 0, 0], [0, 2, 0, 0]])
print("Predicted Value:", pred)

Predicted Value: [0 1]


In [ ]:
# This predictions of no and yes match the manual calculated predictions in the middle of this notebook.