<html>
<body>
<h1 style="background-color: #022851;"><center>
    <br><font size="+3.5">
    <font color=#FFBF00><b>Introduction to Machine Learning</b></font>
   </font>
    <br><font size="+1">
    <font color=#FFBF00><b>WEEK 1 | PROBLEM SET 1 (Numpy) </b></font>
   </font>
    <br><font size="+1">
    <font color=#FFBF00><b>Name:</b> Blue Ferdinand Alday </font> <br>
    <font color=#FFBF00><b>Due Date:</b> 9/15/2024 </font>
   </font> 
    </center>
</h1>
</body>
</html>


In [1]:
import numpy as np

from numpy import random

# needed for Question number 5

## Instructions
1. Do not import any other library. 
2. This assignment primarily focuses on getting a hands on practise for numpy library.
3. Examples are given for most of the questions. You are free to take different values inside the arrays as long as the requirements are questions are met.
4. We have referenced the 1D array as sample_1 and 2D array as sample_2 in the notebook. You are free to change the variable's name.
5. Go through these resources in order ro learn and practise numpy operations : <a href="https://www.w3schools.com/python/numpy/numpy_intro.asp">Resource 1 </a> , <a href="https://realpython.com/numpy-tutorial/">Resource 2 </a>
6. You can also read the documentation of all numpy functions from this <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">Link </a>

#### <b> <font color='red'> Que 1.1 - Defining a numpy matrix </b>   -> Define a 1D numpy array having 6 elements. Print the dimensions, rows and columns of the array </font>

<br> <b>  Example </b> </br>
sample_1 = [ 5, 6, 2, 7, 8, 8]
  - Array dimension = 1
  - Number of rows = 1
  - Number of columns = 6



In [2]:
# define the 1d array
# WRITE CODE BELOW
sample_1 = np.array([5, 6, 2, 7, 8, 8])

In [3]:
# printing the 1D array that you have defined above
print(f"sample_1 = {sample_1}")

# print the dimension, rows and columns of the array
# WRITE CODE BELOW

print(f"Array dimension = {sample_1.ndim}")

# since 1 dimensional arrays do not return the row count, assign row count appropriately
if sample_1.ndim > 1:
    rows = sample_1.shape[1]
else:
    rows = 1

print(f"Number of rows = {rows}")

print(f"Number of columns = {sample_1.shape[0]}")

sample_1 = [5 6 2 7 8 8]
Array dimension = 1
Number of rows = 1
Number of columns = 6


#### <b> <font color='red'> Que 1.2 - Defining a numpy matrix </b>   -> Define a 2D numpy array having 4 rows and 3 columns. Print the dimensions, rows and columns of the array </font>

<br> <b>  Example </b> </br>
$$\begin{bmatrix} 6 & 2 & 1  \\ 3 & 0 & 1 \\ 0 & 2 & 4  \\ 5 & 6 & 8 \end{bmatrix}$$

  - Array dimension = 2
  - Number of rows = 4
  - Number of columns = 3





In [4]:
# define the 2d array
# WRITE CODE BELOW
sample_2 = np.array([[6, 2, 1], [3, 0, 1], [0, 2, 4], [5, 6, 8]])

In [5]:
# printing the 2D array that you have defined above
print(f"sample_2 = \n{sample_2}\n")

# print the dimension, rows and columns of the array
# WRITE CODE BELOW

print(f"Array dimension = {sample_2.ndim}")

# Check dimensional array value since row size is not defined in 1D arrays
if sample_2.ndim > 1:
    rows = sample_2.shape[0]
else:
    rows = 1

print(f"Number of rows = {rows}")

print(f"Number of columns = {sample_2.shape[1]}")

sample_2 = 
[[6 2 1]
 [3 0 1]
 [0 2 4]
 [5 6 8]]

Array dimension = 2
Number of rows = 4
Number of columns = 3


#### <b> <font color='red'> Que 2.1 - Accessing elements </b>   -> Print the first element of 1D array and 2D array that you have defined in the previous question </font>

<br> <b>  Example - Accessing first element of sample_1 and sample_2 defined in prev que</b> </br>
- first_sample1 = 2
- first_sample2 = 6

Note - You can get different output if you have defined different elements in your arrays.



In [6]:
# access first element from both 1D array and 2D array
# WRITE CODE BELOW
# first element of 1D array
first_sample1 = sample_1[0]
print(f"first_sample1 = {first_sample1}")

# first element of 2D array

# Assume the first element of 2D array is the first element in the first row
first_sample2 = sample_2[0, 0]
print(f"first_sample2 = {first_sample2}")

first_sample1 = 5
first_sample2 = 6


#### <b> <font color='red'> Que 2.2 - Array Slicing </b>  </font>  
<font color='red'> 
1. Print first three elements of sample_1 (1D array)
2. Print all elements from second column from sample_2  (2D array) 
3. Print all elements which which belongs to (3rd and 4th row) and (2nd and 3rd column) from sample_2 (2d Array)

<br> <b>  Example - Output for sample_1 and sample_2 array that were defined in the first que</b> </br>
<br> first_three_sample1 = [5, 6 ,2] </br>
<br> second_col_sample2 = [ 2, 0 , 2 , 6] </br>
<br> result_sample2 = 
$$\begin{bmatrix} 2 & 4  \\ 6 & 8  \end{bmatrix}$$



In [7]:
# define three variables
# first three variables of sample_1 (1D array)

# slice first 3 elements in array
first_three_sample1 = sample_1[:3]
print(f"first_three_sample1 = {first_three_sample1}")

# print all elements from second column from sample_2 (2D array)
second_col_sample2 = sample_2[0:, 1]
print(f"second_col_sample2 = {second_col_sample2}")

# print all elements from 3rd and 4th row and 2nd and 3rd column from sample_2 (2D array)
result_sample2 = sample_2[2:4, 1:3]
print(f"\nresult_sample2 = \n{result_sample2}")

first_three_sample1 = [5 6 2]
second_col_sample2 = [2 0 2 6]

result_sample2 = 
[[2 4]
 [6 8]]


#### <b> <font color='red'> Que 3 - Sorting the array - Sort the 1D array (sample_1)  and print it</b>  </font>  

<br> <b>  Example - Output for sample_1  array that was defined in the first que</b> </br>
sorted_sample_1 = [ 2, 5, 6, 7, 8, 8 ]

In [8]:
# sort the 1D array (sample_1)
# WRITE code below
# use the sort function
sorted_sample_1 = np.sort(sample_1)
print(f"sorted_sample_1 = {sorted_sample_1}")

sorted_sample_1 = [2 5 6 7 8 8]


#### <b> <font color='red'> Que 4 - Finding the mean and maximum value of rows and columns </font>  </b>

<font color='red'> 
1. Find the mean of sample_1 (1D array). </font>
<font color='red'> 
2. Find the maximum value from each column of sample_2 (2D array). </font>


<br> <b>  Example - Output for sample_1 and sample_2 array that were defined in the first que </b> </br>
<br>mean_sample_1 =      6.0 </br>
<br>max_column_sample2 = [6, 6 , 8] </br>

In [9]:
# mean of  one_d array
# Write code below
# use the mean function
mean_sample1 = np.mean(sample_1)
print(f"mean_sample1 = {mean_sample1}")


# max value from each column
# write code below
# use the max function against axis=0 for columns
max_column_sample2 = np.max(sample_2, axis=0)
print(f"max_column_sample2 = {max_column_sample2}")

mean_sample1 = 6.0
max_column_sample2 = [6 6 8]


#### <b> <font color='red'>Que 5 - Defining a random numpy array with given shape </font></b>
<font color='red'> Take two inputs from the user <b>num_rows</b> and <b> num_cols</b>, you have to define a random numpy matrix with dimensions (num_rows x num_cols) 
Hint - You can use numpy.random function </font>

In [10]:
print("Enter the number of rows")
num_rows = int(input())
print("Enter the number of columns")
num_cols = int(input())

Enter the number of rows
10
Enter the number of columns
20


In [11]:
# define a random matrix of size (num_rows x num_cols)
# WRITE Code below

# generate numbers between 0 and 100 using the rows and columns from the user
random_array = random.randint(100, size=(num_rows, num_cols))
print(f"random_array = \n{random_array}")

random_array = 
[[95 62 45 33 38  8 73  1 27 52 16 54 65 16 51 13 61  6 92 17]
 [69  6 59 58 70 77 81  0 94 34 81 97 23 80 38 70 26 76  7 99]
 [ 1 63 86 49 55 13 35 39 88 37 16 44 93 45 70 26 10 53 83 26]
 [47 51 21 35 87 99 12 71 55 99 72 71 37 91 56 21 37 67 39 85]
 [89  9 25 45 47 48 50 36  7 13 35 32 32 83 24 69 27 34 24 16]
 [61 92 50 17 92 83 82 29 45 46 38 86 14 73 10 73  8 57 27 13]
 [41 40 81 87 50 27 48  4 53 52 13 33 37 38 98 83 16  2  7  0]
 [ 3 96 61 35 38 26  1 34 52 39 30 52 30 72 83 11 38 19 75 17]
 [42 51  9 81 59 46 78 48 61 39 41  7 34 32 28 38 48 77 63 51]
 [81 15 78 63 78 86 85 65 15 40 77 24 59  8 26 63  3 68 19  4]]


#### <b> <font color='red'>Que 6.1 - Elementwise Multiplication and Matrix multiplication  </font></b>
<font color='red'> There are two ways of multiplication of numpy arrays. The first one is element wise multiplication, where you have to multiply both arrays elementwise.  </font>
<font color='red'> Define two 1D matrices having 4 elements each, and multiply them elementwise. </font>

<br> <b>  Example </b> </br>

<br> array_1 = [2 , 3, 4 , 5] </br>
<br> array_2 = [3,  4,  5,  6] </br>
<br> result_array = [6, 12 , 20, 30 ] </br>




In [12]:
array_1 = np.array([2, 3, 4, 5])
array_2 = np.array([3, 4, 5, 6])

# multiply these two arrays
# store the result in result_array

# use the multiply function
result_array = np.multiply(array_1, array_2)

print(f"array_1 = {array_1}")
print(f"array_2 = {array_2}")
print(f"result_array = {result_array}")

array_1 = [2 3 4 5]
array_2 = [3 4 5 6]
result_array = [ 6 12 20 30]


#### <b> <font color='red'>Que 6.2 - Elementwise Multiplication and Matrix multiplication  </font></b>
<font color='red'> The second one is matrix multiplication, where you have to multiply both arrays according to standard matrix multiplication.  </font>
<font color='red'> Define two 2D matrices first_one of size 2X5 and second_one of size 5X2. Perform matrix mutiplication and print shape of resultant array. </font>

<br> <b>  Example </b> </br>
<br> If you perform matrix multiplication of array_1 and array_2  </br>
array_1  = $$\begin{bmatrix} 1 & 3 &4 &5 &6  \\ 2 &5 &7 &8&9  \end{bmatrix}$$
array_2  = $$\begin{bmatrix} 2 & 4  \\ 2 & 6 \\0 &3 \\8 & 0 \\ 1&4   \end{bmatrix}$$

 will get the resultant array as 
$$\begin{bmatrix} 54 & 58  \\ 87 & 95  \end{bmatrix}$$

In [13]:
array_1 = np.array([[1, 3, 4, 5, 6], [2, 5, 7, 8, 9]])
array_2 = np.array([[2, 4], [2, 6], [0, 3], [8, 0], [1, 4]])

# multiply these two arrays using matrix multiplication
# store the result in result_array
# use the built in matmul function to perform matrix multiplication

result_array = np.matmul(array_1, array_2)

print(f"array_1 = \n{array_1}\n")
print(f"array_2 = \n{array_2}\n")
print(f"result_array = \n{result_array}\n")
print(f"result_array's shape = {result_array.shape}")

array_1 = 
[[1 3 4 5 6]
 [2 5 7 8 9]]

array_2 = 
[[2 4]
 [2 6]
 [0 3]
 [8 0]
 [1 4]]

result_array = 
[[54 58]
 [87 95]]

result_array's shape = (2, 2)


#### <b> <font color='red'>Que 7 - Creating a copy of array</font></b>
<font color='red'> Define a matrix named original_array with some values. Create a copy of this array named copy_array. Now change the first element of the copy_array and then print original_array and copy_array.
<br> Note - While printing you have to make sure that only the copy_array is changed and not the original_array.</br></font>

<b> Example </b>
- original_array = [2 , 4 ,6 , 8]
- copy_array = [ 2, 4, 6 ,8 ]
<br> Modify the first element of copy array to 10 and then print both arrays </br>
- original_array = [2 ,4, 6, 8]
- copy_array = [10, 4, 6, 8]



In [14]:
# define your original_array and copy array
# WRITE CODE BELOW
original_array = np.array([2, 4, 6, 8])

# make a copy
copy_array = original_array.copy()

# print out both arrays before any modification
print("Before modifications,")
print(f"\toriginal_array = {original_array}")
print(f"\tcopy_array = {copy_array}")

# modify the first element of copy_array
copy_array[0] = 0

# print both original and copy_array
print("\nAfter modifications,")
print(f"\tFirst element of original_array = {original_array[0]}")
print(f"\tFirst element of copy_array = {copy_array[0]}")

Before modifications,
	original_array = [2 4 6 8]
	copy_array = [2 4 6 8]

After modifications,
	First element of original_array = 2
	First element of copy_array = 0


#### <b> <font color='red'> Que 8 - Concatenating the arrays along different axes</b> </font>
<font color='red'> Given two matrices array_1 and array_2 as follows </font>

array_1 = $$\begin{bmatrix} 10 & 20  \\ 30 & 40  \end{bmatrix}$$
array_2 = $$\begin{bmatrix} 50 & 60  \\ 70 & 80  \end{bmatrix}$$

<font color='red'> You have to concatenate array_1 and array_2 row-wise and column wise such that the result matrices are as follows.

row_concat_array = $$\begin{bmatrix} 10 & 20  \\ 30 & 40 \\ 50 & 60  \\ 70 & 80  \end{bmatrix}$$
col_concat_array = $$\begin{bmatrix} 10 & 20 & 50 & 60  \\ 30 & 40  & 70 &80 \end{bmatrix}$$


In [15]:
# Defining array_1 and array_2
array_1 = np.array([[10, 20], [30, 40]])
array_2 = np.array([[50, 60], [70, 80]])

# concatenate both the arrays row wise and column wise
# WRITE CODE BELOW

# concatenate the rows without passing an axis
row_concat_array = np.concatenate((array_1, array_2))

# concatenate the columns and pass the axis value
col_concat_array = np.concatenate((array_1, array_2), axis=1)

# print out the arrays
print(f"row_concat_array = \n{row_concat_array}\n")
print(f"col_concat_array = \n{col_concat_array}\n")

row_concat_array = 
[[10 20]
 [30 40]
 [50 60]
 [70 80]]

col_concat_array = 
[[10 20 50 60]
 [30 40 70 80]]



#### <b> <font color='red'> Que 8 Broadcasting the arrays </b>
If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes </font>

<font color='red'> Que 8.1 - Consider an array my_array of size 1 x 5 . Increment each element of the array by 1 and store it in  result _array</font>

<b> Example </b>
<br> my_array = [ 5 , 12, 7 ,3] </br>
<br> result_array = [ 6, 13 , 8, 4]. </br>


In [16]:
# define my_array
my_array = np.array([5, 12, 7, 3])

# Increment each element of my_array by 1
# WRITE CODE BELOW
result_array = my_array + 1

print(f"my_array = {my_array}")
print(f"result_array = {result_array}")

my_array = [ 5 12  7  3]
result_array = [ 6 13  8  4]


<font color='red'> Que 2 - Consider an array of size of size 3x3 . You have to increment each element of column 1 by 5, column 2 by 10 and column 3 by 15. </font> </br>
my_array = $$\begin{bmatrix} 5 & 0 & 3  \\ 3 & 4 & 6 \\ 8& 0 & 7 \end{bmatrix}$$

result_array = $$\begin{bmatrix} 10 & 10 & 18  \\ 8 & 14 & 21 \\ 13 & 10 & 22 \end{bmatrix}$$

In [17]:
# define my_array
my_array = np.array([[5, 0, 3], [3, 4, 6], [8, 0, 7]])

# Increment column_1 by 5, column_2 by 10 and column_3 by 15
# WRITE CODE BELOW

# create an array that contains what you need to increment my_array by
increment_array = np.array([5, 10, 15])

# use the built in add function to increment my_array as instructed and store it in result_array
result_array = np.add(my_array, increment_array)

# print out the arrays
print(f"my_array =\n{my_array}\n")
print(f"result_array =\n{result_array}\n")

my_array =
[[5 0 3]
 [3 4 6]
 [8 0 7]]

result_array =
[[10 10 18]
 [ 8 14 21]
 [13 10 22]]



#<b> END OF ASSIGNMENT <b>